"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";

const LANGUAGES = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "zh", name: "简体中文", flag: "🇨🇳" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" },
];

const LOCALES: Record<string, Record<string, string>> = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "Last Updated: May 26, 2026",
    backHome: "← Back to Home",
    sec1Title: "1. Introduction",
    sec1Desc: 'Welcome to "Are You Okay?". We respect your privacy and are committed to protecting your personal data. This privacy policy explains how we handle, collect, and safeguard your information when you use our emotional tracking mobile application and website services.',
    sec2Title: "2. Data We Collect",
    sec2Desc: "To provide our daily check-in and safety alert services, we may collect the following categories of information:",
    sec2Bullet1: "<strong>Profile Information:</strong> Name, birth year, gender, and profile photo, which helps customize your dashboard.",
    sec2Bullet2: "<strong>Emotional Log Data:</strong> Your daily check-in entries, logged mood tags, optional written journals, and optional voice notes.",
    sec2Bullet3: "<strong>Emergency Contacts:</strong> Email addresses of trusted family members or friends that you explicitly choose to notify if you become inactive.",
    sec3Title: "3. How We Use Your Data",
    sec3Desc: "We utilize your information solely to deliver and improve the &quot;Are You Okay?&quot; experience, specifically to:",
    sec3Bullet1: "Track your emotional health history and streak progression.",
    sec3Bullet2: "Deliver secure alert notifications to your trusted contacts if you fail to check in for your preset duration.",
    sec3Bullet3: "Provide empathetic advice generated by our AI counselor.",
    sec3Bullet4: "We <strong>do NOT sell</strong> your personal data or emotional logs to any third-party advertisers.",
    sec4Title: "4. Data Storage & Security",
    sec4Desc: "All personal information, written journals, and voice records are safely stored on secure Supabase servers. We implement industry-standard encryption and security measures to protect against unauthorized access, disclosure, or alteration of your emotional data.",
    sec5Title: "5. In-App Subscriptions & Billing",
    sec5Desc: "We offer in-app purchases and auto-renewable subscriptions (Pro and Premium tiers) to unlock advanced features. All billing, purchases, and subscriptions are securely processed and verified through Apple App Store (iOS) or Google Play Store (Android) using the RevenueCat SDK.",
    sec6Title: "6. Children&apos;s Privacy",
    sec6Desc: "Our services are intended for a general audience. We do not knowingly collect personal identifiable information from children under the age of 13. If you believe a child has provided us with personal data, please contact us immediately to have it deleted.",
    sec7Title: "7. Contact Us",
    sec7Desc: "If you have any questions or feedback regarding this Privacy Policy or your personal data, please contact our support team at:",
    footerRights: "© 2026 Are You Okay? Team. All rights reserved.",
  },
  vi: {
    title: "Chính sách Bảo mật",
    lastUpdated: "Cập nhật lần cuối: 26 tháng 5, 2026",
    backHome: "← Quay lại trang chủ",
    sec1Title: "1. Giới thiệu",
    sec1Desc: 'Chào mừng bạn đến với "Are You Okay?". Chúng tôi tôn trọng quyền riêng tư của bạn và cam kết bảo vệ dữ liệu cá nhân của bạn. Chính sách bảo mật này giải thích cách chúng tôi xử lý, thu thập và bảo vệ thông tin của bạn khi bạn sử dụng ứng dụng theo dõi cảm xúc và dịch vụ website của chúng tôi.',
    sec2Title: "2. Dữ liệu Chúng tôi Thu thập",
    sec2Desc: "Để cung cấp dịch vụ check-in hàng ngày và cảnh báo an toàn, chúng tôi có thể thu thập các loại thông tin sau:",
    sec2Bullet1: "<strong>Thông tin hồ sơ:</strong> Tên, năm sinh, giới tính và ảnh đại diện, giúp cá nhân hóa bảng điều khiển của bạn.",
    sec2Bullet2: "<strong>Dữ liệu cảm xúc:</strong> Các mục check-in hàng ngày, thẻ cảm xúc, nhật ký văn bản tùy chọn và ghi âm giọng nói tùy chọn.",
    sec2Bullet3: "<strong>Liên hệ khẩn cấp:</strong> Địa chỉ email của các thành viên gia đình hoặc bạn bè đáng tin cậy mà bạn chọn để thông báo nếu bạn ngừng hoạt động.",
    sec3Title: "3. Cách Chúng tôi Sử dụng Dữ liệu của Bạn",
    sec3Desc: "Chúng tôi sử dụng thông tin của bạn chỉ để cung cấp và cải thiện trải nghiệm &quot;Are You Okay?&quot;, cụ thể là:",
    sec3Bullet1: "Theo dõi lịch sử sức khỏe cảm xúc và tiến trình chuỗi ngày của bạn.",
    sec3Bullet2: "Gửi thông báo cảnh báo an toàn đến các liên hệ đáng tin cậy nếu bạn không check-in trong khoảng thời gian đã đặt.",
    sec3Bullet3: "Cung cấp lời khuyên đồng cảm do AI tạo ra.",
    sec3Bullet4: "Chúng tôi <strong>KHÔNG bán</strong> dữ liệu cá nhân hoặc nhật ký cảm xúc của bạn cho bất kỳ bên thứ ba nào.",
    sec4Title: "4. Lưu trữ & Bảo mật Dữ liệu",
    sec4Desc: "Tất cả thông tin cá nhân, nhật ký văn bản và bản ghi âm được lưu trữ an toàn trên máy chủ Supabase. Chúng tôi triển khai các biện pháp mã hóa và bảo mật theo tiêu chuẩn ngành để bảo vệ khỏi truy cập trái phép, tiết lộ hoặc thay đổi dữ liệu cảm xúc của bạn.",
    sec5Title: "5. Đăng ký & Thanh toán Trong Ứng dụng",
    sec5Desc: "Chúng tôi cung cấp các giao dịch mua trong ứng dụng và gói đăng ký tự động gia hạn (Pro và Premium) để mở khóa các tính năng nâng cao. Tất cả các hóa đơn, giao dịch mua và đăng ký đều được xử lý và xác minh an toàn thông qua Apple App Store (iOS) hoặc Google Play Store (Android) bằng SDK RevenueCat.",
    sec6Title: "6. Quyền riêng tư của Trẻ em",
    sec6Desc: "Dịch vụ của chúng tôi dành cho đối tượng tổng quát. Chúng tôi không cố tình thu thập thông tin nhận dạng cá nhân từ trẻ em dưới 13 tuổi. Nếu bạn tin rằng trẻ em đã cung cấp dữ liệu cá nhân cho chúng tôi, vui lòng liên hệ ngay để xóa dữ liệu đó.",
    sec7Title: "7. Liên hệ Chúng tôi",
    sec7Desc: "Nếu bạn có bất kỳ câu hỏi hoặc phản hồi nào về Chính sách Bảo mật này hoặc dữ liệu cá nhân của bạn, vui lòng liên hệ với nhóm hỗ trợ của chúng tôi tại:",
    footerRights: "© 2026 Are You Okay? Team. Tất cả các quyền được bảo lưu.",
  },
  zh: {
    title: "隐私政策",
    lastUpdated: "最后更新：2026年5月26日",
    backHome: "← 返回首页",
    sec1Title: "1. 简介",
    sec1Desc: '欢迎使用"Are You Okay?"。我们尊重您的隐私并致力于保护您的个人数据。本隐私政策说明了当您使用我们的情绪追踪移动应用和网站服务时，我们如何处理、收集和保护您的信息。',
    sec2Title: "2. 我们收集的数据",
    sec2Desc: "为了提供每日签到和安全提醒服务，我们可能会收集以下类别的信息：",
    sec2Bullet1: "<strong>个人资料信息：</strong>姓名、出生年份、性别和个人资料照片，用于定制您的仪表板。",
    sec2Bullet2: "<strong>情绪日志数据：</strong>您的每日签到记录、情绪标签、可选的文字日记和可选的语音笔记。",
    sec2Bullet3: "<strong>紧急联系人：</strong>您明确选择在您不活跃时通知的可信家庭成员或朋友的电子邮件地址。",
    sec3Title: "3. 我们如何使用您的数据",
    sec3Desc: "我们仅使用您的信息来提供和改善&ldquo;Are You Okay?&rdquo;体验，具体包括：",
    sec3Bullet1: "跟踪您的情绪健康历史和连续记录。",
    sec3Bullet2: "如果您未在预设时间内签到，向您的可信联系人发送安全提醒通知。",
    sec3Bullet3: "提供由AI顾问生成的共情建议。",
    sec3Bullet4: "我们<strong>不出售</strong>您的个人数据或情绪日志给任何第三方广告商。",
    sec4Title: "4. 数据存储与安全",
    sec4Desc: "所有个人信息、文字日记和语音记录均安全存储在Supabase服务器上。我们采用行业标准的加密和安全措施，防止未经授权的访问、披露或篡改您的情绪数据。",
    sec5Title: "5. 应用内订阅与计费",
    sec5Desc: "我们提供应用内购买和自动续订订阅（专业版和高级版）以解锁高级功能。所有计费、购买和订阅均通过Apple App Store（iOS）或Google Play Store（Android）使用RevenueCat SDK安全处理和验证。",
    sec6Title: "6. 儿童隐私",
    sec6Desc: "我们的服务面向普通用户。我们不会故意收集13岁以下儿童的个人身份信息。如果您认为儿童向我们提供了个人数据，请立即联系我们删除。",
    sec7Title: "7. 联系我们",
    sec7Desc: "如果您对本隐私政策或您的个人数据有任何疑问或反馈，请通过以下方式联系我们的支持团队：",
    footerRights: "© 2026 Are You Okay? 团队。保留所有权利。",
  },
  ja: {
    title: "プライバシーポリシー",
    lastUpdated: "最終更新日: 2026年5月26日",
    backHome: "← ホームに戻る",
    sec1Title: "1. はじめに",
    sec1Desc: '"Are You Okay?"へようこそ。当社はお客様のプライバシーを尊重し、個人データの保護に努めています。このプライバシーポリシーは、お客様が当社の感情追跡モバイルアプリケーションおよびウェブサイトサービスをご利用になる際に、お客様の情報をどのように取り扱い、収集し、保護するかを説明するものです。',
    sec2Title: "2. 収集するデータ",
    sec2Desc: "毎日のチェックインおよび安全アラートサービスを提供するために、以下のカテゴリの情報を収集する場合があります：",
    sec2Bullet1: "<strong>プロフィール情報：</strong>氏名、生年、性別、プロフィール写真。ダッシュボードのカスタマイズに使用されます。",
    sec2Bullet2: "<strong>感情ログデータ：</strong>毎日のチェックイン記録、気分タグ、オプションのテキストジャーナル、オプションのボイスノート。",
    sec2Bullet3: "<strong>緊急連絡先：</strong>お客様が非アクティブになった場合に通知するよう明示的に選択した信頼できる家族または友人のメールアドレス。",
    sec3Title: "3. データの使用方法",
    sec3Desc: "お客様の情報は、&quot;Are You Okay?&quot;エクスペリエンスを提供および改善するためだけに使用されます。具体的には以下の目的で使用されます：",
    sec3Bullet1: "感情の健康履歴と継続記録の追跡。",
    sec3Bullet2: "設定された期間内にチェックインがない場合、信頼できる連絡先へのセキュアなアラート通知の送信。",
    sec3Bullet3: "AIカウンセラーによる共感的なアドバイスの提供。",
    sec3Bullet4: "お客様の個人データや感情ログを第三者広告主に<strong>販売することはありません</strong>。",
    sec4Title: "4. データストレージとセキュリティ",
    sec4Desc: "すべての個人情報、テキストジャーナル、音声記録は安全なSupabaseサーバーに保存されます。当社は業界標準の暗号化およびセキュリティ対策を実施し、お客様の感情データへの不正アクセス、開示、改ざんを防止します。",
    sec5Title: "5. アプリ内購読と請求",
    sec5Desc: "ProおよびPremiumティアの自動更新サブスクリプションを通じて高度な機能を提供しています。すべての請求、購入、サブスクリプションは、RevenueCat SDKを使用してApple App Store（iOS）またはGoogle Play Store（Android）を通じて安全に処理および検証されます。",
    sec6Title: "6. 子どものプライバシー",
    sec6Desc: "当社のサービスは一般ユーザーを対象としています。13歳未満の子どもから個人識別情報を意図的に収集することはありません。お子様が当社に個人データを提供したと思われる場合は、直ちに削除するようご連絡ください。",
    sec7Title: "7. お問い合わせ",
    sec7Desc: "本プライバシーポリシーまたはお客様の個人データに関するご質問やご意見がございましたら、以下のサポートチームまでご連絡ください：",
    footerRights: "© 2026 Are You Okay? チーム。無断転載を禁じます。",
  },
  ko: {
    title: "개인정보 처리방침",
    lastUpdated: "최근 업데이트: 2026년 5월 26일",
    backHome: "← 홈으로 돌아가기",
    sec1Title: "1. 소개",
    sec1Desc: '"Are You Okay?"에 오신 것을 환영합니다. 당사는 귀하의 개인정보를 존중하며 개인 데이터를 보호하기 위해 최선을 다하고 있습니다. 본 개인정보 처리방침은 귀하가 당사의 감정 추적 모바일 애플리케이션 및 웹사이트 서비스를 사용할 때 당사가 귀하의 정보를 처리, 수집 및 보호하는 방법을 설명합니다.',
    sec2Title: "2. 수집하는 데이터",
    sec2Desc: "일일 체크인 및 안전 알림 서비스를 제공하기 위해 당사는 다음과 같은 범주의 정보를 수집할 수 있습니다:",
    sec2Bullet1: "<strong>프로필 정보:</strong> 이름, 출생 연도, 성별 및 프로필 사진. 대시보드 맞춤 설정에 사용됩니다.",
    sec2Bullet2: "<strong>감정 로그 데이터:</strong> 일일 체크인 기록, 기분 태그, 선택적 텍스트 일기 및 선택적 음성 메모.",
    sec2Bullet3: "<strong>비상 연락처:</strong> 귀하가 비활성 상태가 될 경우 알림을 받도록 선택한 신뢰할 수 있는 가족 또는 친구의 이메일 주소.",
    sec3Title: "3. 데이터 사용 방법",
    sec3Desc: "당사는 귀하의 정보를 &quot;Are You Okay?&quot; 경험을 제공하고 개선하기 위해서만 사용합니다. 구체적으로:",
    sec3Bullet1: "감정 건강 기록 및 연속 기록 추적.",
    sec3Bullet2: "설정된 기간 내에 체크인하지 않을 경우 신뢰할 수 있는 연락처에 안전한 알림 전송.",
    sec3Bullet3: "AI 상담사가 생성한 공감적 조언 제공.",
    sec3Bullet4: "당사는 귀하의 개인 데이터나 감정 로그를 제3자 광고주에게 <strong>판매하지 않습니다</strong>.",
    sec4Title: "4. 데이터 저장 및 보안",
    sec4Desc: "모든 개인 정보, 텍스트 일기 및 음성 기록은 안전한 Supabase 서버에 저장됩니다. 당사는 업계 표준 암호화 및 보안 조치를 구현하여 귀하의 감정 데이터에 대한 무단 액세스, 공개 또는 변경을 방지합니다.",
    sec5Title: "5. 인앱 구독 및 결제",
    sec5Desc: "당사는 고급 기능을 잠금 해제하기 위해 인앱 구매 및 자동 갱신 구독(Pro 및 Premium 등급)을 제공합니다. 모든 청구, 구매 및 구독은 RevenueCat SDK를 사용하여 Apple App Store(iOS) 또는 Google Play Store(Android)를 통해 안전하게 처리 및 확인됩니다.",
    sec6Title: "6. 어린이 개인정보 보호",
    sec6Desc: "당사의 서비스는 일반 대상을 대상으로 합니다. 당사는 13세 미만의 어린이로부터 개인 식별 정보를 의도적으로 수집하지 않습니다. 어린이가 당사에 개인 데이터를 제공했다고 생각되면 즉시 삭제할 수 있도록 연락해 주십시오.",
    sec7Title: "7. 문의하기",
    sec7Desc: "본 개인정보 처리방침 또는 귀하의 개인 데이터에 관한 질문이나 피드백이 있으시면 다음 연락처로 지원팀에 문의해 주십시오:",
    footerRights: "© 2026 Are You Okay? 팀. All rights reserved.",
  },
  es: {
    title: "Política de Privacidad",
    lastUpdated: "Última actualización: 26 de mayo de 2026",
    backHome: "← Volver al inicio",
    sec1Title: "1. Introducción",
    sec1Desc: 'Bienvenido a "Are You Okay?". Respetamos su privacidad y estamos comprometidos a proteger sus datos personales. Esta política de privacidad explica cómo manejamos, recopilamos y protegemos su información cuando utiliza nuestra aplicación móvil de seguimiento emocional y los servicios del sitio web.',
    sec2Title: "2. Datos que Recopilamos",
    sec2Desc: "Para proporcionar nuestros servicios de registro diario y alertas de seguridad, podemos recopilar las siguientes categorías de información:",
    sec2Bullet1: "<strong>Información de perfil:</strong> Nombre, año de nacimiento, género y foto de perfil, que ayuda a personalizar su tablero.",
    sec2Bullet2: "<strong>Datos de registro emocional:</strong> Sus entradas de registro diario, etiquetas de estado de ánimo, diarios escritos opcionales y notas de voz opcionales.",
    sec2Bullet3: "<strong>Contactos de emergencia:</strong> Direcciones de correo electrónico de familiares o amigos de confianza que elige explícitamente para notificar si se vuelve inactivo.",
    sec3Title: "3. Cómo Usamos Sus Datos",
    sec3Desc: "Utilizamos su información únicamente para brindar y mejorar la experiencia de &quot;Are You Okay?&quot;, específicamente para:",
    sec3Bullet1: "Realizar un seguimiento de su historial de salud emocional y progreso de racha.",
    sec3Bullet2: "Enviar notificaciones de alerta seguras a sus contactos de confianza si no se registra durante el período establecido.",
    sec3Bullet3: "Proporcionar consejos empáticos generados por nuestro consejero de IA.",
    sec3Bullet4: "<strong>NO vendemos</strong> sus datos personales ni registros emocionales a ningún anunciante externo.",
    sec4Title: "4. Almacenamiento y Seguridad de Datos",
    sec4Desc: "Toda la información personal, diarios escritos y registros de voz se almacenan de forma segura en servidores Supabase. Implementamos medidas de cifrado y seguridad de estándar industrial para proteger contra el acceso no autorizado, la divulgación o la alteración de sus datos emocionales.",
    sec5Title: "5. Suscripciones y Facturación en la Aplicación",
    sec5Desc: "Ofrecemos compras integradas y suscripciones de renovación automática (niveles Pro y Premium) para desbloquear funciones avanzadas. Toda la facturación, compras y suscripciones se procesan y verifican de forma segura a través de Apple App Store (iOS) o Google Play Store (Android) utilizando el SDK de RevenueCat.",
    sec6Title: "6. Privacidad Infantil",
    sec6Desc: "Nuestros servicios están dirigidos a un público general. No recopilamos a sabiendas información de identificación personal de niños menores de 13 años. Si cree que un niño nos ha proporcionado datos personales, comuníquese con nosotros de inmediato para eliminarlos.",
    sec7Title: "7. Contáctenos",
    sec7Desc: "Si tiene alguna pregunta o comentario sobre esta Política de Privacidad o sus datos personales, comuníquese con nuestro equipo de soporte en:",
    footerRights: "© 2026 Are You Okay? Team. Todos los derechos reservados.",
  },
  pt: {
    title: "Política de Privacidade",
    lastUpdated: "Última atualização: 26 de maio de 2026",
    backHome: "← Voltar ao início",
    sec1Title: "1. Introdução",
    sec1Desc: 'Bem-vindo ao "Are You Okay?". Respeitamos a sua privacidade e estamos comprometidos em proteger os seus dados pessoais. Esta política de privacidade explica como tratamos, recolhemos e protegemos as suas informações quando utiliza a nossa aplicação móvel de monitorização emocional e serviços do site.',
    sec2Title: "2. Dados que Recolhemos",
    sec2Desc: "Para fornecer os nossos serviços de registo diário e alertas de segurança, podemos recolher as seguintes categorias de informação:",
    sec2Bullet1: "<strong>Informações de perfil:</strong> Nome, ano de nascimento, género e foto de perfil, que ajudam a personalizar o seu painel.",
    sec2Bullet2: "<strong>Dados de registo emocional:</strong> As suas entradas diárias de registo, etiquetas de humor, diários escritos opcionais e notas de voz opcionais.",
    sec2Bullet3: "<strong>Contactos de emergência:</strong> Endereços de email de familiares ou amigos de confiança que escolhe explicitamente para notificar se ficar inativo.",
    sec3Title: "3. Como Usamos os Seus Dados",
    sec3Desc: "Utilizamos as suas informações exclusivamente para fornecer e melhorar a experiência &quot;Are You Okay?&quot;, especificamente para:",
    sec3Bullet1: "Monitorizar o seu histórico de saúde emocional e progresso de sequência.",
    sec3Bullet2: "Enviar notificações de alerta seguras aos seus contactos de confiança se não fizer o registo dentro do período definido.",
    sec3Bullet3: "Fornecer conselhos empáticos gerados pelo nosso conselheiro de IA.",
    sec3Bullet4: "<strong>NÃO vendemos</strong> os seus dados pessoais ou registos emocionais a terceiros anunciantes.",
    sec4Title: "4. Armazenamento e Segurança de Dados",
    sec4Desc: "Todas as informações pessoais, diários escritos e gravações de voz são armazenados de forma segura em servidores Supabase. Implementamos medidas de encriptação e segurança de padrão industrial para proteger contra acesso não autorizado, divulgação ou alteração dos seus dados emocionais.",
    sec5Title: "5. Subscrições e Faturação na Aplicação",
    sec5Desc: "Oferecemos compras na aplicação e subscrições com renovação automática (níveis Pro e Premium) para desbloquear funcionalidades avançadas. Toda a faturação, compras e subscrições são processadas e verificadas de forma segura através da Apple App Store (iOS) ou Google Play Store (Android) utilizando o SDK RevenueCat.",
    sec6Title: "6. Privacidade de Crianças",
    sec6Desc: "Os nossos serviços destinam-se a um público geral. Não recolhemos intencionalmente informações pessoais identificáveis de crianças com menos de 13 anos. Se acreditar que uma criança nos forneceu dados pessoais, contacte-nos imediatamente para os eliminar.",
    sec7Title: "7. Fale Connosco",
    sec7Desc: "Se tiver alguma dúvida ou comentário sobre esta Política de Privacidade ou os seus dados pessoais, contacte a nossa equipa de suporte em:",
    footerRights: "© 2026 Are You Okay? Team. Todos os direitos reservados.",
  },
  hi: {
    title: "गोपनीयता नीति",
    lastUpdated: "अंतिम अपडेट: 26 मई, 2026",
    backHome: "← मुख्य पृष्ठ पर जाएं",
    sec1Title: "1. परिचय",
    sec1Desc: '"Are You Okay?" में आपका स्वागत है। हम आपकी गोपनीयता का सम्मान करते हैं और आपके व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध हैं। यह गोपनीयता नीति बताती है कि जब आप हमारे भावनात्मक ट्रैकिंग मोबाइल एप्लिकेशन और वेबसाइट सेवाओं का उपयोग करते हैं तो हम आपकी जानकारी को कैसे संभालते हैं, एकत्र करते हैं और सुरक्षित करते हैं।',
    sec2Title: "2. हम जो डेटा एकत्र करते हैं",
    sec2Desc: "अपनी दैनिक चेक-इन और सुरक्षा अलर्ट सेवाएं प्रदान करने के लिए, हम निम्नलिखित श्रेणियों की जानकारी एकत्र कर सकते हैं:",
    sec2Bullet1: "<strong>प्रोफ़ाइल जानकारी:</strong> नाम, जन्म वर्ष, लिंग और प्रोफ़ाइल फ़ोटो, जो आपके डैशबोर्ड को अनुकूलित करने में मदद करता है।",
    sec2Bullet2: "<strong>भावनात्मक लॉग डेटा:</strong> आपकी दैनिक चेक-इन प्रविष्टियां, लॉग किए गए मूड टैग, वैकल्पिक लिखित जर्नल और वैकल्पिक वॉइस नोट्स।",
    sec2Bullet3: "<strong>आपातकालीन संपर्क:</strong> विश्वसनीय परिवार के सदस्यों या मित्रों के ईमेल पते जिन्हें आप निष्क्रिय होने पर सूचित करने के लिए स्पष्ट रूप से चुनते हैं।",
    sec3Title: "3. हम आपके डेटा का उपयोग कैसे करते हैं",
    sec3Desc: "हम आपकी जानकारी का उपयोग केवल &quot;Are You Okay?&quot; अनुभव प्रदान करने और बेहतर बनाने के लिए करते हैं, विशेष रूप से:",
    sec3Bullet1: "आपके भावनात्मक स्वास्थ्य इतिहास और स्ट्रीक प्रगति को ट्रैक करना।",
    sec3Bullet2: "यदि आप अपनी निर्धारित अवधि के लिए चेक इन करने में विफल रहते हैं तो आपके विश्वसनीय संपर्कों को सुरक्षित अलर्ट सूचनाएं भेजना।",
    sec3Bullet3: "हमारे AI काउंसलर द्वारा उत्पन्न सहानुभूतिपूर्ण सलाह प्रदान करना।",
    sec3Bullet4: "हम आपके व्यक्तिगत डेटा या भावनात्मक लॉग को किसी तीसरे पक्ष के विज्ञापनदाताओं को <strong>नहीं बेचते</strong> हैं।",
    sec4Title: "4. डेटा भंडारण और सुरक्षा",
    sec4Desc: "सभी व्यक्तिगत जानकारी, लिखित जर्नल और वॉइस रिकॉर्ड सुरक्षित Supabase सर्वर पर संग्रहीत किए जाते हैं। हम आपके भावनात्मक डेटा तक अनधिकृत पहुंच, प्रकटीकरण या परिवर्तन से बचाने के लिए उद्योग-मानक एन्क्रिप्शन और सुरक्षा उपायों को लागू करते हैं।",
    sec5Title: "5. इन-ऐप सदस्यता और बिलिंग",
    sec5Desc: "हम उन्नत सुविधाओं को अनलॉक करने के लिए इन-ऐप खरीदारी और ऑटो-नवीकरणीय सदस्यता (Pro और Premium टियर) प्रदान करते हैं। सभी बिलिंग, खरीदारी और सदस्यताएं RevenueCat SDK का उपयोग करके Apple App Store (iOS) या Google Play Store (Android) के माध्यम से सुरक्षित रूप से संसाधित और सत्यापित की जाती हैं।",
    sec6Title: "6. बच्चों की गोपनीयता",
    sec6Desc: "हमारी सेवाएं सामान्य दर्शकों के लिए हैं। हम जानबूझकर 13 वर्ष से कम उम्र के बच्चों से व्यक्तिगत पहचान योग्य जानकारी एकत्र नहीं करते हैं। यदि आपको लगता है कि किसी बच्चे ने हमें व्यक्तिगत डेटा प्रदान किया है, तो कृपया उसे हटाने के लिए तुरंत हमसे संपर्क करें।",
    sec7Title: "7. हमसे संपर्क करें",
    sec7Desc: "यदि आपके पास इस गोपनीयता नीति या आपके व्यक्तिगत डेटा के बारे में कोई प्रश्न या प्रतिक्रिया है, तो कृपया हमारी सहायता टीम से यहां संपर्क करें:",
    footerRights: "© 2026 Are You Okay? टीम। सर्वाधिकार सुरक्षित।",
  },
  id: {
    title: "Kebijakan Privasi",
    lastUpdated: "Terakhir Diperbarui: 26 Mei 2026",
    backHome: "← Kembali ke Beranda",
    sec1Title: "1. Pengantar",
    sec1Desc: '"Are You Okay?" dengan hormat. Kami menghormati privasi Anda dan berkomitmen untuk melindungi data pribadi Anda. Kebijakan privasi ini menjelaskan bagaimana kami menangani, mengumpulkan, dan menjaga informasi Anda saat Anda menggunakan aplikasi pelacakan emosional seluler dan layanan situs web kami.',
    sec2Title: "2. Data yang Kami Kumpulkan",
    sec2Desc: "Untuk menyediakan layanan check-in harian dan peringatan keselamatan, kami dapat mengumpulkan kategori informasi berikut:",
    sec2Bullet1: "<strong>Informasi Profil:</strong> Nama, tahun lahir, jenis kelamin, dan foto profil, yang membantu menyesuaikan dasbor Anda.",
    sec2Bullet2: "<strong>Data Log Emosional:</strong> Entri check-in harian Anda, tag suasana hati yang dicatat, jurnal tertulis opsional, dan catatan suara opsional.",
    sec2Bullet3: "<strong>Kontak Darurat:</strong> Alamat email anggota keluarga atau teman tepercaya yang Anda pilih secara eksplisit untuk diberi tahu jika Anda menjadi tidak aktif.",
    sec3Title: "3. Cara Kami Menggunakan Data Anda",
    sec3Desc: "Kami menggunakan informasi Anda semata-mata untuk memberikan dan meningkatkan pengalaman &quot;Are You Okay?&quot;, khususnya untuk:",
    sec3Bullet1: "Melacak riwayat kesehatan emosional dan kemajuan streak Anda.",
    sec3Bullet2: "Mengirimkan notifikasi peringatan aman ke kontak tepercaya Anda jika Anda gagal check-in dalam durasi yang ditentukan.",
    sec3Bullet3: "Memberikan saran empatik yang dihasilkan oleh konselor AI kami.",
    sec3Bullet4: "Kami <strong>TIDAK menjual</strong> data pribadi atau log emosional Anda kepada pengiklan pihak ketiga mana pun.",
    sec4Title: "4. Penyimpanan & Keamanan Data",
    sec4Desc: "Semua informasi pribadi, jurnal tertulis, dan rekaman suara disimpan dengan aman di server Supabase. Kami menerapkan enkripsi dan langkah-langkah keamanan standar industri untuk melindungi dari akses tidak sah, pengungkapan, atau perubahan data emosional Anda.",
    sec5Title: "5. Langganan & Tagihan Dalam Aplikasi",
    sec5Desc: "Kami menawarkan pembelian dalam aplikasi dan langganan perpanjangan otomatis (tingkat Pro dan Premium) untuk membuka fitur lanjutan. Semua tagihan, pembelian, dan langganan diproses dan diverifikasi dengan aman melalui Apple App Store (iOS) atau Google Play Store (Android) menggunakan SDK RevenueCat.",
    sec6Title: "6. Privasi Anak-anak",
    sec6Desc: "Layanan kami ditujukan untuk khalayak umum. Kami tidak dengan sengaja mengumpulkan informasi identitas pribadi dari anak-anak di bawah usia 13 tahun. Jika Anda yakin seorang anak telah memberikan data pribadi kepada kami, harap segera hubungi kami untuk menghapusnya.",
    sec7Title: "7. Hubungi Kami",
    sec7Desc: "Jika Anda memiliki pertanyaan atau masukan mengenai Kebijakan Privasi ini atau data pribadi Anda, silakan hubungi tim dukungan kami di:",
    footerRights: "© 2026 Are You Okay? Team. Semua hak dilindungi undang-undang.",
  },
};

export default function PrivacyPolicy() {
  const [lang, setLang] = useState<string>("en");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      const urlLang = params.get("lang");
      if (urlLang && LOCALES[urlLang]) {
        setLang(urlLang);
        return;
      }

      const browserLang = navigator.language.split("-")[0];
      if (LOCALES[browserLang]) {
        setLang(browserLang);
      }
    }
  }, []);

  const t = LOCALES[lang] || LOCALES.en;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-blue-600 selection:text-white py-16 px-6 relative overflow-x-hidden">
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none -translate-y-1/2"></div>

      <div className="max-w-3xl mx-auto space-y-12 relative z-10">
        <div className="flex items-center justify-between border-b border-slate-900 pb-8">
          <Link href="/" className="flex items-center gap-2 group">
            <span className="text-slate-400 group-hover:text-white transition-colors">{t.backHome}</span>
          </Link>
          <div className="flex items-center gap-4">
            <div className="relative">
              <select
                value={lang}
                onChange={(e) => setLang(e.target.value)}
                className="appearance-none bg-slate-900 border border-slate-800 text-xs font-semibold text-blue-400 hover:border-blue-500 hover:text-white transition-all rounded-full px-4 py-2 pr-8 cursor-pointer active:scale-95 outline-none"
              >
                {LANGUAGES.map((l) => (
                  <option key={l.code} value={l.code} className="bg-slate-950 text-slate-100 font-sans">
                    {l.flag} {l.name}
                  </option>
                ))}
              </select>
              <div className="absolute inset-y-0 right-3 flex items-center pointer-events-none text-blue-400/80">
                <svg className="w-3.5 h-3.5 fill-current" viewBox="0 0 20 20">
                  <path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" />
                </svg>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-lg">💙</span>
              <span className="font-extrabold text-sm text-white">Are You Okay?</span>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <h1 className="text-4xl font-black text-white tracking-tight">{t.title}</h1>
          <p className="text-sm text-slate-500 font-mono">{t.lastUpdated}</p>
        </div>

        <div className="space-y-8 text-slate-300 leading-relaxed text-sm">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec1Title}</h2>
            <p>{t.sec1Desc}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec2Title}</h2>
            <p>{t.sec2Desc}</p>
            <ul className="list-disc pl-6 space-y-2">
              <li dangerouslySetInnerHTML={{ __html: t.sec2Bullet1 }} />
              <li dangerouslySetInnerHTML={{ __html: t.sec2Bullet2 }} />
              <li dangerouslySetInnerHTML={{ __html: t.sec2Bullet3 }} />
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec3Title}</h2>
            <p>{t.sec3Desc}</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>{t.sec3Bullet1}</li>
              <li>{t.sec3Bullet2}</li>
              <li>{t.sec3Bullet3}</li>
              <li dangerouslySetInnerHTML={{ __html: t.sec3Bullet4 }} />
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec4Title}</h2>
            <p>{t.sec4Desc}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec5Title}</h2>
            <p>{t.sec5Desc}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec6Title}</h2>
            <p>{t.sec6Desc}</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">{t.sec7Title}</h2>
            <p>{t.sec7Desc}</p>
            <p className="font-semibold text-blue-400 mt-2">
              Email: loverhide.blog@gmail.com
            </p>
          </section>
        </div>

        <div className="border-t border-slate-900 pt-8 text-center text-xs text-slate-600">
          <p>{t.footerRights}</p>
        </div>
      </div>
    </div>
  );
}
