"use client";

import React from "react";
import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-blue-600 selection:text-white py-16 px-6 relative overflow-x-hidden">
      {/* Background Gradients */}
      <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none -translate-y-1/2"></div>

      <div className="max-w-3xl mx-auto space-y-12 relative z-10">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-900 pb-8">
          <Link href="/" className="flex items-center gap-2 group">
            <span className="text-slate-400 group-hover:text-white transition-colors">← Back to Home</span>
          </Link>
          <div className="flex items-center gap-2">
            <span className="text-lg">💙</span>
            <span className="font-extrabold text-sm text-white">Are You Okay?</span>
          </div>
        </div>

        {/* Title */}
        <div className="space-y-4">
          <h1 className="text-4xl font-black text-white tracking-tight">Privacy Policy</h1>
          <p className="text-sm text-slate-500 font-mono">Last Updated: May 26, 2026</p>
        </div>

        {/* Policy Content */}
        <div className="space-y-8 text-slate-300 leading-relaxed text-sm">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">1. Introduction</h2>
            <p>
              Welcome to "Are You Okay?". We respect your privacy and are committed to protecting your personal data. This privacy policy explains how we handle, collect, and safeguard your information when you use our emotional tracking mobile application and website services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">2. Data We Collect</h2>
            <p>
              To provide our daily check-in and safety alert services, we may collect the following categories of information:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Profile Information:</strong> Name, birth year, gender, and profile photo, which helps customize your dashboard.
              </li>
              <li>
                <strong>Emotional Log Data:</strong> Your daily check-in entries, logged mood tags, optional written journals, and optional voice notes.
              </li>
              <li>
                <strong>Emergency Contacts:</strong> Email addresses of trusted family members or friends that you explicitly choose to notify if you become inactive.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">3. How We Use Your Data</h2>
            <p>
              We utilize your information solely to deliver and improve the "Are You Okay?" experience, specifically to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Track your emotional health history and streak progression.</li>
              <li>Deliver secure alert notifications to your trusted contacts if you fail to check in for your preset duration.</li>
              <li>Provide empathetic advice generated by our AI counselor.</li>
              <li>We <strong>do NOT sell</strong> your personal data or emotional logs to any third-party advertisers.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">4. Data Storage & Security</h2>
            <p>
              All personal information, written journals, and voice records are safely stored on secure Supabase servers. We implement industry-standard encryption and security measures to protect against unauthorized access, disclosure, or alteration of your emotional data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">5. In-App Subscriptions & Billing</h2>
            <p>
              We offer in-app purchases and auto-renewable subscriptions (Pro and Premium tiers) to unlock advanced features. All billing, purchases, and subscriptions are securely processed and verified through Apple App Store (iOS) or Google Play Store (Android) using the **RevenueCat SDK**.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">6. Children's Privacy</h2>
            <p>
              Our services are intended for a general audience. We do not knowingly collect personal identifiable information from children under the age of 13. If you believe a child has provided us with personal data, please contact us immediately to have it deleted.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">7. Contact Us</h2>
            <p>
              If you have any questions or feedback regarding this Privacy Policy or your personal data, please contact our support team at:
            </p>
            <p className="font-semibold text-blue-400 mt-2">
              Email: loverhide.blog@gmail.com
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="border-t border-slate-900 pt-8 text-center text-xs text-slate-600">
          <p>© 2026 Are You Okay? Team. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
